# Dependencies
markdown:	redcarpet
# Permalinks
permalink: /:categories/:year/:month/:day/:title 

# Setup
baseurl:

title:		盛利的博客
tagline:	'blog'
description:	'专注大数据，分布式计算，Spark Contributor.'
url:		http://oopsoutofmemory.github.io
commentsystem:	google
disqus:		shengli

author:
  name:		'OopsOutOfMemory'
  url:		http://oopsoutofmemory.github.io

paginate:	5

# Custom vars
icon:		/assets/images/oopsoutofmemory.jpg
cover:		/assets/images/cover.jpg


comments :
  provider : duoshuo
  duoshuo : 
    short_name : oopsoutofmemory


menu:
  - title:	首页
    url: /

  - title:  博客列表
    url:  /category.html

  - title:	关于我
    url:  /aboutMe.html

  - title:  Test 404
    url:  /404

markdown: redcarpet  

copyright:
  author:	盛利
  url:		http://oopsoutofmemory.github.io
  type_title:  All rights reserved
  type_url:	http://oopsoutofmemory.github.io

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:
